# Generated by Django 5.1.2 on 2024-10-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=5, verbose_name="Розмір")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
            ],
            options={
                "verbose_name": "Розмір",
                "verbose_name_plural": "Розміри",
                "db_table": "size",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Категорія")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Url"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/category",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                        verbose_name="Підкатегорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Ціна"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=150, unique=True, verbose_name="Url"
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Колір")),
                ("article", models.CharField(max_length=30, verbose_name="Артикул")),
                ("material", models.CharField(max_length=100, verbose_name="Матеріал")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("AUTUMN", "Осінь"),
                            ("SUMMER", "Літо"),
                            ("WINTER", "Зима"),
                            ("SPRING", "Весна"),
                        ],
                        default="WINTER",
                        max_length=10,
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Кількість"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Взуття",
                "verbose_name_plural": "Взуття",
                "db_table": "product",
                "ordering": ["-created_at", "updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Зображення"),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення",
                "verbose_name_plural": "Галерея товарів",
                "db_table": "gallery",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Кількість")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.size",
                        verbose_name="Розмір",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "size"), name="unique_product_size"
                    )
                ],
            },
        ),
    ]
